# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# relative_permalinks: true

# Setup
title:            YM
tagline:          "Yeongmo's Page"
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://yeongmo-j.github.io
baseurl:          /

author:
  name:           'yeongmo j'
  url:            https://yeongmo-j.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://yeongmo-j.github.io
